name: Deploy to GH pages

on: 
  push:
    branches:
      - pdn
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          node-version: 20
          package-manager: pnpm@latest
          # path: . # The root location of your Astro project inside the repository. (optional)
  # if i add another job here i have to add another jobs like:
    # upload the artifact, in this case no because i use the action withastro/action@v3 and it does it for me cause i have the build step and next the deploy if i add another job here i have to add the upload artifact step
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4